SELECT * FROM PIZZA_SALES

------KPI's REQUIREMENTS------

--TOTAL REVENUE:
SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM PIZZA_SALES;

--AVERAGE ORDER VALUE:
SELECT SUM(TOTAL_PRICE) / COUNT(DISTINCT ORDER_ID) AS AVG_ORDER_VALUE FROM PIZZA_SALES;

--TOTAL PIZZAS SOLD:
SELECT SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD FROM PIZZA_SALES;

--TOTAL ORDERS:
SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES;

--AVERAGE PIZZAS PER ORDER:
SELECT CAST(CAST(SUM(QUANTITY) AS DECIMAL(10,2)) / 
CAST(COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2)) AS DECIMAL(10,2))
AS AVG_PIZZAS_PER_ORDER
FROM PIZZA_SALES;

------CHARTS REQUIREMENTS------

--DAILY TREND FOR TOTAL ORDERS:
SELECT DATENAME(DW, ORDER_DATE) AS ORDER_DAY, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY DATENAME(DW, ORDER_DATE);

--MONTHLY TREND FOR TOTAL ORDERS:
SELECT DATENAME(MONTH, ORDER_DATE) AS MONTH_NAME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY DATENAME(MONTH, ORDER_DATE)
ORDER BY TOTAL_ORDERS DESC;

--PERCENTAGE OF SALES BY PIZZA CATEGORY:
SELECT PIZZA_CATEGORY,SUM(TOTAL_PRICE) AS TOTAL_SALES, SUM(TOTAL_PRICE) * 100 /
(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES
WHERE MONTH(ORDER_DATE) = 1) AS PCT
FROM PIZZA_SALES
WHERE MONTH(ORDER_DATE) = 1
GROUP BY PIZZA_CATEGORY; 

--PERCENTAGE OF SALES BY PIZZA SIZE:
SELECT PIZZA_SIZE,CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2)) AS TOTAL_SALES, CAST(SUM(TOTAL_PRICE) * 100 /
(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES WHERE DATEPART(QUARTER, ORDER_DATE) = 1) AS DECIMAL(10,2)) AS PCT
FROM PIZZA_SALES
WHERE DATEPART(QUARTER, ORDER_DATE) = 1
GROUP BY PIZZA_SIZE
ORDER BY PCT DESC;

--TOTAL PIZZAS SOLD BY PIZZA CATEGORY:
SELECT PIZZA_CATEGORY, COUNT(DISTINCT ORDER_ID) AS TOTAL_SALES
FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY;

--TOP 5 BEST SELLERS BY TOTAL PIZZAS SOLD:
SELECT TOP 5 PIZZA_NAME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDERS DESC

--BOTTOM 5 WORST SELLERS BY TOTAL PIZZAS SOLD:
SELECT TOP 5 PIZZA_NAME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDERS ASC

